services:
  sabine:
    build: 
      context: .
      dockerfile: apps/sabine/Dockerfile
      secrets:
        - env
    image: sabine
    container_name: sabine
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - apps/sabine/.env
    environment:
      - REDIS_URL=redis://localhost:6379
      - NODE_ENV=production
    network_mode: host

  helper:
    build: 
      context: .
      dockerfile: apps/helper/Dockerfile
      secrets:
        - env
    image: sabine-helper
    container_name: sabine-helper
    restart: unless-stopped
    env_file:
      - apps/helper/.env
    network_mode: host

  web:
    build: 
      context: .
      dockerfile: apps/web/Dockerfile
      secrets:
        - env
    image: sabine-website
    container_name: sabine-website
    restart: always
    env_file:
      - apps/web/.env
    network_mode: host

  api:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
      secrets:
        - env
    image: sabine-api
    container_name: sabine-api
    restart: always
    env_file:
      - apps/api/.env
    network_mode: host

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --bind localhost
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli replicaof no one && redis-cli ping']
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    network_mode: host
    shm_size: 2gb
    
    environment:
      - PGDATA=/var/lib/postgresql/18/data
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/18/data
      - ./postgres/backup:/var/lib/postgresql/18/backup

    command: >
      postgres
      -c shared_buffers=1536MB
      -c work_mem=4MB
      -c effective_cache_size=5GB
      -c random_page_cost=1.1

    healthcheck:
      test: ['CMD-SHELL', 'PGPASSWORD=$${POSTGRES_PASSWORD} pg_isready -h localhost -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-backup:
    image: postgres:18
    container_name: postgres-backup
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./postgres/backup:/var/lib/postgresql/18/backup
    entrypoint: >
      bash -c "
      while true; do
        echo 'Backing up...'
        PGPASSWORD=$${POSTGRES_PASSWORD} pg_dumpall -h localhost -U $${POSTGRES_USER} > /var/lib/postgresql/18/backup/tmp.sql && \
        mv /var/lib/postgresql/18/backup/tmp.sql /var/lib/postgresql/18/backup/backup_$$(date +%Y%m%d%H%M).sql
        ls -tp /var/lib/postgresql/18/backup/backup_*.sql | tail -n +11 | xargs -I {} rm -- {}
        echo 'Done'
        sleep 86400
      done
      "

volumes:
  redis_data:

secrets:
  env:
    file: ./.env