name: Biome Format and Check
on:
  push:
    branches: ["**"]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'README*'
      - 'LICENSE'
      - 'crowdin.yml'
      - '.github/**'
  pull_request:
    branches: ["**"]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'README*'
      - 'LICENSE'
      - 'crowdin.yml'
      - '.github/**'

jobs:
  format-and-review:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}
          persist-credentials: true
          
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          
      - name: Attempt to implement Biome fixes
        run: |
          biome check --write --no-errors-on-unmatched . || echo "Issues found, attempting auto-commit..."

      - name: Get co-author noreply email
        run: |
          ID=$(curl -s \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/levisantosp | jq -r .id)
          echo "COAUTHOR_EMAIL=${ID}+levisantosp@users.noreply.github.com" >> $GITHUB_ENV
          
      - name: Commit changes
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: |
            fix(lint): implement automatic biome fixes

            Co-authored-by: levisantosp <${{ env.COAUTHOR_EMAIL }}>
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          
      - name: Run Biome via Reviewdog (PR Only)
        if: github.event_name == 'pull_request'
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_level: error
          workdir: .